permalink: /:year:month:day/:title
url: https://1337.hackermindset.me
baseurl: /

# variables
name: The Hacker Mindset
description: Always learning...
google_verification: null

# theme: jekyll-theme-windows95

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : false
