permalink: /:year:month:day/:title
url: https://ualvesdias.github.io #Your url here
baseurl: /

# variables
name: You're Exposed!
description: Always learning...
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true