permalink: /:year:month:day/:title
url: https://ualvesdias.github.io #Your url here
baseurl: /mysite

# variables
name: Ulisses Alves
description: Just a guy learning about infosec
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
