# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-04-19 18:18:50 -0300 by Odysseus:
gem "jekyll", "~> 3.8"
